In [12]:
import pandas as pd
import seaborn as sns

In [13]:
df = pd.read_csv(r'C:\Users\ishay\Downloads\IPL_Auction_2022_FullList.csv')

In [19]:
df

,Set No.,Set Name,Player,Country,State Association,Age,Specialism,Batting,Bowling,IPL,Previous IPLTeam(s),2021 Team,C/U/A,Base Price,Sold Price,New Franchise,Bid
0,1,M,Trent Boult,New Zealand,NaN,32,BOWLER,RHB,LEFT ARM Fast Medium,62.0,"SRH, KKR, DD,MI",MI,Capped,200,8 CR,Rajasthan Royals,Sold
1,1,M,Pat Cummins,Australia,NaN,28,ALL-ROUNDER,RHB,RIGHT ARM Fast,37.0,"DD, MI, KKR",KKR,Capped,200,7.25 CR,Kolkata Knight Riders,Sold
2,1,M,Shikhar Dhawan,India,DDCA,36,BATSMAN,LHB,-,192.0,"DCH, MI, SRH, DC",DC,Capped,200,8.25 CR,Punjab Kings,Sold
3,1,M,Shreyas Iyer,India,MCA,27,BATSMAN,RHB,RIGHT ARM Leg Spin,87.0,DC,DC,Capped,200,12.25 CR,Kolkata Knight Riders,Sold
4,1,M,Kagiso Rabada,South Africa,NaN,26,BOWLER,LHB,RIGHT ARM Fast,50.0,DC,DC,Capped,200,9.25 CR,Punjab Kings,Sold
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,62,UAL15,Safyaan Sharif,Scotland,NaN,30,ALL-ROUNDER,RHB,RIGHT ARM Fast Medium,NaN,NaN,NaN,Associate,20,NaN,NaN,UnSold
585,62,UAL15,Henry Shipley,New Zealand,NaN,25,ALL-ROUNDER,RHB,RIGHT ARM Fast Medium,NaN,NaN,NaN,Uncapped,20,NaN,NaN,UnSold
586,62,UAL15,Maxwell Swaminathan,India,MCA,23,ALL-ROUNDER,RHB,RIGHT ARM Off Spin,NaN,NaN,NaN,Uncapped,20,NaN,NaN,UnSold
587,62,UAL15,Johan Van Dyk,South Africa,NaN,28,ALL-ROUNDER,RHB,RIGHT ARM Fast Medium,NaN,NaN,NaN,Uncapped,20,NaN,NaN,UnSold
588,62,UAL15,Dunith Wellalage,Sri Lanka,NaN,19,ALL-ROUNDER,LHB,LEFT ARM Slow Orthodox,NaN,NaN,NaN,Uncapped,20,NaN,NaN,UnSold

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 589 entries, 0 to 588
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Set No.              589 non-null    int64
 1   Set Name             589 non-null    object
 2   Player               589 non-null    object
 3   Country              589 non-null    object
 4   State Association    369 non-null    object
 5   Age                  589 non-null    int64
 6   Specialism           589 non-null    object
 7   Batting              589 non-null    object
 8   Bowling              589 non-null    object
 9   IPL                  270 non-null    float64
 10  Previous IPLTeam(s)  265 non-null    object
 11  2021 Team            165 non-null    object
 12  C/U/A                589 non-null    object
 13  Base Price           589 non-null    int64
 14  Sold Price           204 non-null    object
 15  New Franchise        204 non-null    object
 16  Bid                  589 non-null    object
dtypes: float64(1), int64(3), object(13)
memory usage: 78.4+ KB

In [15]:
df.isnull().sum()

Set No.                  0
Set Name                 0
Player                   0
Country                  0
State Association      220
Age                      0
Specialism               0
Batting                  0
Bowling                  0
IPL                    319
Previous IPLTeam(s)    324
2021 Team              424
C/U/A                    0
Base Price               0
Sold Price             385
New Franchise          385
Bid                      0
dtype: int64

In [16]:
df.shape

(589, 17)

Bowling:

Classify into 4 groups - left fast, left spin , right fast, right spin

Create 3 columns: left fast, left spin, right fast
000 = right spin
010 = left spin
100 = left fast
001 = Right fast

In [17]:
df.Bowling.unique()

array(['LEFT ARM Fast Medium', 'RIGHT ARM Fast', '-',
       'RIGHT ARM Leg Spin', 'RIGHT ARM Off Spin',
       'RIGHT ARM Fast Medium', 'LEFT ARM Slow Orthodox', 'LEFT ARM Fast',
       'LEFT ARM Slow Unorthodox', 'RIGHT ARM Medium', 'LEFT ARM Medium'],
      dtype=object)

In [18]:
df

,Set No.,Set Name,Player,Country,State Association,Age,Specialism,Batting,Bowling,IPL,Previous IPLTeam(s),2021 Team,C/U/A,Base Price,Sold Price,New Franchise,Bid
0,1,M,Trent Boult,New Zealand,NaN,32,BOWLER,RHB,LEFT ARM Fast Medium,62.0,"SRH, KKR, DD,MI",MI,Capped,200,8 CR,Rajasthan Royals,Sold
1,1,M,Pat Cummins,Australia,NaN,28,ALL-ROUNDER,RHB,RIGHT ARM Fast,37.0,"DD, MI, KKR",KKR,Capped,200,7.25 CR,Kolkata Knight Riders,Sold
2,1,M,Shikhar Dhawan,India,DDCA,36,BATSMAN,LHB,-,192.0,"DCH, MI, SRH, DC",DC,Capped,200,8.25 CR,Punjab Kings,Sold
3,1,M,Shreyas Iyer,India,MCA,27,BATSMAN,RHB,RIGHT ARM Leg Spin,87.0,DC,DC,Capped,200,12.25 CR,Kolkata Knight Riders,Sold
4,1,M,Kagiso Rabada,South Africa,NaN,26,BOWLER,LHB,RIGHT ARM Fast,50.0,DC,DC,Capped,200,9.25 CR,Punjab Kings,Sold
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,62,UAL15,Safyaan Sharif,Scotland,NaN,30,ALL-ROUNDER,RHB,RIGHT ARM Fast Medium,NaN,NaN,NaN,Associate,20,NaN,NaN,UnSold
585,62,UAL15,Henry Shipley,New Zealand,NaN,25,ALL-ROUNDER,RHB,RIGHT ARM Fast Medium,NaN,NaN,NaN,Uncapped,20,NaN,NaN,UnSold
586,62,UAL15,Maxwell Swaminathan,India,MCA,23,ALL-ROUNDER,RHB,RIGHT ARM Off Spin,NaN,NaN,NaN,Uncapped,20,NaN,NaN,UnSold
587,62,UAL15,Johan Van Dyk,South Africa,NaN,28,ALL-ROUNDER,RHB,RIGHT ARM Fast Medium,NaN,NaN,NaN,Uncapped,20,NaN,NaN,UnSold
588,62,UAL15,Dunith Wellalage,Sri Lanka,NaN,19,ALL-ROUNDER,LHB,LEFT ARM Slow Orthodox,NaN,NaN,NaN,Uncapped,20,NaN,NaN,UnSold

## Specialisation

Create 2 columns:

00 = Batsman
01 =